TugasAkhir/TugasAkhir/Controllers/suratsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TugasAkhir.Models;

namespace TugasAkhir.Controllers
{
    public class suratsController : Controller
    {
        private dbOpsModel db = new dbOpsModel();

//Awal rekening
        public ActionResult IndexRekening()
        {
            if (Session["nik"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (Session["jabatan"].ToString() == "k")
            {
                return RedirectToAction("Karyawan", "Login");
            }
            return View();
        }   
        public ActionResult RequestRekening()
        {
            return View(GetRequestRekening());
        }

        IEnumerable<surat> GetRequestRekening()
        {
            var rekening = db.surats.Include(u => u.detail_surat).Include(x => x.jenis_surat).Where(u => u.id_jenis == 1 && u.status == "Request").OrderBy(u => u.tanggal);
            return rekening.ToList();
        }

        public ActionResult ProcessRekening()
        {
            return View(GetProcessRekening());
        }

        IEnumerable<surat> GetProcessRekening()
        {
            var rekening = db.surats.Include(u => u.detail_surat).Include(x => x.jenis_surat).Where(u => u.id_jenis == 1 && u.status == "Process").OrderBy(u => u.tanggal);
            return rekening.ToList();
        }

        public ActionResult RiwayatRekening()
        {
            return View(GetRiwayatRekening());
        }

        IEnumerable<surat> GetRiwayatRekening()
        {
            var rekening = db.surats.Include(u => u.detail_surat).Include(x => x.jenis_surat).Where(u => u.id_jenis == 1 && u.status == "Finish").OrderBy(u => u.tanggal);
            return rekening.ToList();
        }

        public ActionResult EditStatusRekening(int id)
        {
            surat rekening = db.surats.Where(u => u.id_surat == id).FirstOrDefault();
            if (rekening.status == "Request")
            {
                rekening.status = "Process";
                db.Entry(rekening).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true, html = Global.RenderRazorViewToString(this, "RequestRekening", GetRequestRekening()), message = "Proses Dilanjutkan" }, JsonRequestBehavior.AllowGet);
            }
            else if (rekening.status == "Process")
            {
                rekening.status = "Finish";
                db.Entry(rekening).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true, html = Global.RenderRazorViewToString(this, "ProcessRekening", GetProcessRekening()), message = "Proses Selesai" }, JsonRequestBehavior.AllowGet);
            }
            return Json("Success");
        }

    //loadajax
        public JsonResult JsonProcessRekening()
        {
            return Json(new { success = true, html = Global.RenderRazorViewToString(this, "ProcessRekening", GetProcessRekening()), message = "Proses Selesai" }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult JsonRiwayatRekening()
        {
            return Json(new { success = true, html = Global.RenderRazorViewToString(this, "RiwayatRekening", GetRiwayatRekening()), message = "Proses Selesai" }, JsonRequestBehavior.AllowGet);
        }

 //Ahkir Rekening

 //Awal keterangankerja
        public ActionResult IndexKerja()
        {
            if (Session["nik"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (Session["jabatan"].ToString() == "k")
            {
                return RedirectToAction("Karyawan", "Login");
            }
            return View();
        }
        public ActionResult RequestKerja()
        {
            return View(GetRequestKerja());
        }

        IEnumerable<surat> GetRequestKerja()
        {
            var rekening = db.surats.Include(x => x.jenis_surat).Where(u => u.id_jenis == 2 && u.status == "Request").OrderBy(u => u.tanggal);
            return rekening.ToList();
        }

        public ActionResult ProcessKerja()
        {
            return View(GetProcessKerja());
        }

        IEnumerable<surat> GetProcessKerja()
        {
            var rekening = db.surats.Include(x => x.jenis_surat).Where(u => u.id_jenis == 2 && u.status == "Process").OrderBy(u => u.tanggal);
            return rekening.ToList();
        }

        public ActionResult RiwayatKerja()
        {
            return View(GetRiwayatKerja());
        }

        IEnumerable<surat> GetRiwayatKerja()
        {
            var rekening = db.surats.Include(x => x.jenis_surat).Where(u => u.id_jenis == 2 && u.status == "Finish").OrderBy(u => u.tanggal);
            return rekening.ToList();
        }

        public ActionResult EditStatusKerja(int id)
        {
            surat kerja = db.surats.Where(u => u.id_surat == id).FirstOrDefault();
            if (kerja.status == "Request")
            {
                kerja.status = "Process";
                db.Entry(kerja).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true, html = Global.RenderRazorViewToString(this, "RequestKerja", GetRequestKerja()), message = "Proses Dilanjutkan" }, JsonRequestBehavior.AllowGet);
            }
            else if (kerja.status == "Process")
            {
                kerja.status = "Finish";
                db.Entry(kerja).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true, html = Global.RenderRazorViewToString(this, "ProcessKerja", GetProcessKerja()), message = "Proses Selesai" }, JsonRequestBehavior.AllowGet);
            }
            return Json("Success");
        }

        //loadajax
        public JsonResult JsonProcessKerja()
        {
            return Json(new { success = true, html = Global.RenderRazorViewToString(this, "ProcessKerja", GetProcessKerja()), message = "Proses Selesai" }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult JsonRiwayatKerja()
        {
            return Json(new { success = true, html = Global.RenderRazorViewToString(this, "RiwayatKerja", GetRiwayatKerja()), message = "Proses Selesai" }, JsonRequestBehavior.AllowGet);
        }

        //Ahkir keterangankerja

        //Awal NPWP
        public ActionResult IndexNPWP()
        {
            if (Session["nik"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (Session["jabatan"].ToString() == "k")
            {
                return RedirectToAction("Karyawan", "Login");
            }
            return View();
        }
        public ActionResult RequestNPWP()
        {
            return View(GetRequestNPWP());
        }

        IEnumerable<surat> GetRequestNPWP()
        {
            var rekening = db.surats.Include(x => x.jenis_surat).Include(u => u.detail_surat).Where(u => u.id_jenis == 3 && u.status == "Request").OrderBy(u => u.tanggal);
            return rekening.ToList();
        }

        public ActionResult ProcessNPWP()
        {
            return View(GetProcessNPWP());
        }

        IEnumerable<surat> GetProcessNPWP()
        {
            var rekening = db.surats.Include(x => x.jenis_surat).Include(u => u.detail_surat).Where(u => u.id_jenis == 3 && u.status == "Process").OrderBy(u => u.tanggal);
            return rekening.ToList();
        }

        public ActionResult RiwayatNPWP()
        {
            return View(GetRiwayatNPWP());
        }

        IEnumerable<surat> GetRiwayatNPWP()
        {
            var rekening = db.surats.Include(u => u.detail_surat).Include(x => x.jenis_surat).Where(u => u.id_jenis == 3 && u.status == "Finish").OrderBy(u => u.tanggal);
            return rekening.ToList();
        }

        public ActionResult EditStatusNPWP(int id)
        {
            surat npwp = db.surats.Where(u => u.id_surat == id).FirstOrDefault();
            if (npwp.status == "Request")
            {
                npwp.status = "Process";
                db.Entry(npwp).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true, html = Global.RenderRazorViewToString(this, "RequestNPWP", GetRequestNPWP()), message = "Proses Dilanjutkan" }, JsonRequestBehavior.AllowGet);

            }
            else if (npwp.status == "Process")
            {
                npwp.status = "Finish";
                db.Entry(npwp).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true, html = Global.RenderRazorViewToString(this, "ProcessNPWP", GetProcessNPWP()), message = "Proses Selesai" }, JsonRequestBehavior.AllowGet);

            }     
            return Json("Success");
        }

        //loadajax
        public JsonResult JsonProcessNPWP()
        {
            return Json(new { success = true, html = Global.RenderRazorViewToString(this, "ProcessNPWP", GetProcessNPWP()), message = "Proses Selesai" }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult JsonRiwayatNPWP()
        {
            return Json(new { success = true, html = Global.RenderRazorViewToString(this, "RiwayatNPWP", GetRiwayatNPWP()), message = "Proses Selesai" }, JsonRequestBehavior.AllowGet);
        }

//Ahkir NPWP

//Awal Pemberitahuan
        public ActionResult IndexPemberitahuan()
        {
            if (Session["nik"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (Session["jabatan"].ToString() == "k")
            {
                return RedirectToAction("Karyawan", "Login");
            }
            return View();
        }
        public ActionResult RequestPemberitahuan()
        {

TugasAkhir/TugasAkhir/Views/Admin/index.cshtml
@{
    ViewBag.Title = "Admin";
}
<hr style="margin-top:0;">
<div class="row">

    <div class="text-center">
        <img src="@ViewBag.Foto" class="img-circle" style="border:1px;width:100px;border: 5px solid #eaeaea;box-shadow: 1px 1px 10px rgba(0, 0, 0, 0.5);" /><br />
        <h2>Selamat Datang Admin @ViewBag.Nama</h2>
    </div>

</div>

<div class="row">
    <hr />
    <div class="col-md-4">
        <div class="panel panel-success">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-money-bill-alt fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">
                            @if (Convert.ToUInt32(ViewData["NSlipGaji"]) == 0)
                            {
                                <h1 style="margin-top:0;"><b>0</b></h1>
                            }
                            else
                            {
                                <h1 style="margin-top:0; color:red;"><b>@ViewData["NSlipGaji"] </b></h1>
                            }
                        </div>
                        <div><h4><b>Slip Gaji</b></h4></div>
                    </div>
                </div>
            </div>
            <a href="@Url.Action("Index","slipgajis")">
                <div class="panel-footer">
                    <span class="pull-left"><font color="#3c763d">View Details</font></span>
                    <span class="pull-right"><font color="#3c763d"><i class="fa fa-arrow-circle-right"></i></font></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-chalkboard-teacher fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">
                            @if (Convert.ToUInt32(ViewData["NVisa"]) == 0)
                            {
                                <h1 style="margin-top:0;"><b>0</b></h1>
                            }
                            else
                            {
                                <h1 style="margin-top:0; color:red;"><b>@ViewData["NVisa"] </b></h1>
                            }
                        </div>
                        <div><h4><b>Visa</b></h4></div>
                    </div>
                </div>
            </div>
            <a href="@Url.Action("IndexVisa","surats")">
                <div class="panel-footer">
                    <span class="pull-left">View Details</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-ambulance fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">
                            @if (Convert.ToUInt32(ViewData["NClaim"]) == 0)
                            {
                                <h1 style="margin-top:0;"><b>0</b></h1>
                            }
                            else
                            {
                                <h1 style="margin-top:0; color:red;"><b>@ViewData["NClaim"] </b></h1>
                            }
                        </div>
                        <div><h4><b>Claim Medical</b></h4></div>
                    </div>
                </div>
            </div>
            <a href="@Url.Action("Index","claim_medical")">
                <div class="panel-footer">
                    <span class="pull-left"><font color="#a94442">View Details</font></span>
                    <span class="pull-right"><font color="#a94442"><i class="fa fa-arrow-circle-right"></i></font></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
</div>  
@*//Notifikasi Surat*@
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-info">
            <div class="panel-heading" role="tab" id="headingTwo">
                <h4 class="panel-title">

                    <a style="text-decoration-line:none;" class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        <span class="fa fa-bullhorn"></span>
                        <font color="red">
                            @if (Convert.ToUInt32(ViewData["NTotal"]) == 0)
                            {
                                <b>0</b>
                            }
                            else
                            {
                                <b color: red;>@ViewData["NTotal"]</b>
                            }
                        </font> Notifikasi Surat
                    </a>

                </h4>
            </div>
            <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                <div class="panel-body">

                    <div class="row" style="margin-top:10px;">
                        <div class="col-md-3">
                            <div class="panel panel-info">
                                <div class="panel-heading">
                                    <div class="row">
                                        <div class="col-xs-3">
                                            <i class="fa fa-book-open fa-5x"></i>
                                        </div>
                                        <div class="col-xs-9 text-right">
                                            <div class="huge">
                                                @if (Convert.ToUInt32(ViewData["NRekening"]) == 0)
                                                {
                                                    <h1 style="margin-top:0;"><b>0</b></h1>
                                                }
                                                else
                                                {
                                                    <h1 style="margin-top:0; color:red;"><b>@ViewData["NRekening"] </b></h1>
                                                }
                                            </div>
                                            <div><h4><b>Buka Rekening</b></h4></div>
                                        </div>
                                    </div>
                                </div>
                                <a href="@Url.Action("IndexRekening","surats")">
                                    <div class="panel-footer">
                                        <span class="pull-left"><font color="#00BFFF">View Details</font></span>
                                        <span class="pull-right"><font color="#00BFFF"><i class="fa fa-arrow-circle-right"></i></font></span>
                                        <div class="clearfix"></div>
                                    </div>
                                </a>
                            </div>
                        </div>

                        <div class="col-md-3">
                            <div class="panel panel-warning">
                                <div class="panel-heading">
                                    <div class="row">
                                        <div class="col-xs-3">
                                            <i class="fa fa-file-code fa-5x"></i>
                                        </div>
                                        <div class="col-xs-9 text-right">
                                            <div class="huge">
                                                @if (Convert.ToUInt32(ViewData["NNPWP"]) == 0)
                                                {
                                                    <h1 style="margin-top:0;"><b>0</b></h1>
                                                }
                                                else
                                                {
                                                    <h1 style="margin-top:0; color:red;"><b>@ViewData["NNPWP"] </b></h1>
                                                }
                                            </div>
                                            <div><h4><b>NPWP</b></h4></div>
                                        </div>
                                    </div>
                                </div>
                                <a href="@Url.Action("IndexNPWP","surats")">
                                    <div class="panel-footer">
                                        <span class="pull-left"><font color="#8a6d3b">View Details</font></span>
                                        <span class="pull-right"><font color="#8a6d3b"><i class="fa fa-arrow-circle-right"></i></font></span>
                                        <div class="clearfix"></div>
                                    </div>
                                </a>
                            </div>
                        </div>

                        <div class="col-md-3">
                            <div class="panel panel-danger">
                                <div class="panel-heading">
                                    <div class="row">
                                        <div class="col-xs-3">
                                            <i class="fa fa-child fa-5x"></i>
                                        </div>
                                        <div class="col-xs-9 text-right">
                                            <div class="huge">
                                                @if (Convert.ToUInt32(ViewData["NKerja"]) == 0)
                                                {
                                                    <h1 style="margin-top:0;"><b>0</b></h1>
                                                }
                                                else
                                                {
                                                    <h1 style="margin-top:0; color:red;"><b>@ViewData["NKerja"] </b></h1>
                                                }
                                            </div>
                                            <div><h4><b>Keterangan Kerja</b></h4></div>
                                        </div>
                                    </div>
                                </div>
                                <a href="@Url.Action("IndexKerja","surats")">
                                    <div class="panel-footer">
                                        <span class="pull-left"><font color="#a94442">View Details</font></span>
                                        <span class="pull-right"><font color="#a94442"><i class="fa fa-arrow-circle-right"></i></font></span>
                                        <div class="clearfix"></div>
                                    </div>
                                </a>
                            </div>
                        </div>

                        <div class="col-md-3">
                            <div class="panel panel-success">
                                <div class="panel-heading">
                                    <div class="row">
                                        <div class="col-xs-3">
                                            <i class="fa fa-grin-alt fa-5x"></i>
                                        </div>
                                        <div class="col-xs-9 text-right">
                                            <div class="huge">
                                                @if (Convert.ToUInt32(ViewData["NPemberitahuan"]) == 0)
                                                {
                                                    <h1 style="margin-top:0;"><b>0</b></h1>
                                                }
                                                else
                                                {
                                                    <h1 style="margin-top:0; color:red;"><b>@ViewData["NPemberitahuan"] </b></h1>
                                                }
                                            </div>
                                            <div><h4><b>Pemberitahuan</b></h4></div>
                                        </div>
                                    </div>
                                </div>
                                <a href="@Url.Action("IndexPemberitahuan","surats")">
                                    <div class="panel-footer">
                                        <span class="pull-left"><font color="#3c763d">View Details</font></span>
                                        <span class="pull-right"><font color="#3c763d"><i class="fa fa-arrow-circle-right"></i></font></span>
                                        <div class="clearfix"></div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>                   

                </div>
            </div>
        </div>
    </div>
</div>