TugasAkhir/TugasAkhir/Models/lembur.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TugasAkhir.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Web;

    public partial class lembur
    {
        public int id_lembur { get; set; }
        public int nik { get; set; }
        [DisplayFormat(DataFormatString = "{0:hh\\:mm}", ApplyFormatInEditMode = true)]
        public System.TimeSpan jam_mulai { get; set; }
        [DisplayFormat(DataFormatString = "{0:hh\\:mm}", ApplyFormatInEditMode = true)]
        public System.TimeSpan jam_selesai { get; set; }
        public Nullable<System.DateTime> tanggal { get; set; }
        public Nullable<decimal> reward { get; set; }
        public Nullable<decimal> totalreward { get; set; }
        public string status { get; set; }
        public string oleh { get; set; }
        [DisplayFormat(DataFormatString = "{0:hh\\:mm}", ApplyFormatInEditMode = true)]
        public System.TimeSpan total_jam { get; set; }
    
        public virtual user user { get; set; }
    }
}

TugasAkhir/TugasAkhir/Controllers/lembursController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TugasAkhir.Models;

namespace TugasAkhir.Controllers
{
    public class lembursController : Controller
    {
        private dbOpsModel db = new dbOpsModel();

        public ActionResult IndexLemburK()
        {
            if (Session["nik"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (Session["jabatan"].ToString() != "k")
            {
                return RedirectToAction("Admin", "Login");
            }
            return View();
        }

        // Lembur Karyawan
        public ActionResult ListLemburK()
        {
            return View(GetListLemburK());
        }

        IEnumerable<lembur> GetListLemburK()
        {
            int id = Convert.ToInt32(Session["nik"]);
            var lembur = db.lemburs.Where(u => u.nik == id && u.status == "Pending").OrderBy(u => u.tanggal);
            return lembur.ToList();
        }

        public ActionResult RiwayatLemburK()
        {
            return View(GetRiwayatLemburK());
        }

        IEnumerable<lembur> GetRiwayatLemburK()
        {
            int id = Convert.ToInt32(Session["nik"]);
            var lembur = db.lemburs.Where(u => u.nik == id && u.status != "Pending").OrderBy(u => u.tanggal);
            return lembur.ToList();
        }


        //Akhir Lembur karyawan  
        // Lembur admin

        public ActionResult Index()
        {
            if (Session["nik"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (Session["jabatan"].ToString() == "k")
            {
                return RedirectToAction("Karyawan", "Login");
            }
            return View();
        }

        public ActionResult ListLembur()
        {
            return View(GetListLembur());
        }

        IEnumerable<lembur> GetListLembur()
        {
            var lembur = db.lemburs.Include(u => u.user).Where(u => u.status == "Pending").OrderBy(u => u.tanggal);
            return lembur.ToList();
        }

        public ActionResult RiwayatLembur()
        {
            return View(GetRiwayatLembur());
        }

        IEnumerable<lembur> GetRiwayatLembur()
        {
            var lembur = db.lemburs.Include(u => u.user).Where(u => u.status != "Pending").OrderBy(u => u.tanggal);
            return lembur.ToList();
        }


        public ActionResult Create()
        {
            ViewBag.ddnama = new SelectList(db.users.Where(u => u.jabatan == "k" && u.status_kerja == "Aktif"), "nik", "nama");
            return View();
        }

        public JsonResult JsonGetNIP(int id)
        {
            var nip = db.users.Where(u => u.nik == id).FirstOrDefault();
            return Json(nip.nip);
        }

        [HttpPost]
        public ActionResult Create(lembur lembur)
        {
            try
            {             
                var lemburs = db.lemburs.Where(u => u.nik == lembur.nik && u.tanggal == lembur.tanggal).FirstOrDefault();
                if (lemburs != null)
                {
                    return Json(new { success = false, message = "Lembur sudah ada" }, JsonRequestBehavior.AllowGet);
                }
                TimeSpan totallembur = lembur.total_jam;   
                decimal? upahjam = totallembur.Hours * lembur.reward;
                decimal? upahmenit = ((totallembur.Minutes * 100 / 60) * lembur.reward) / 100;
                lembur.totalreward = upahjam + upahmenit; 
                lembur.status = "Pending";
                lembur.oleh = Session["nama"].ToString();
                db.lemburs.Add(lembur);
                db.SaveChanges();
                return Json(new { success = true, html = Global.RenderRazorViewToString(this, "ListLembur", GetListLembur()), message = "Input Data Sukses" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult EditStatus(int[] check)
        {
            try
            {
                if (check == null)
                {
                    return Json(new { success = false, message = "Check Minimal 1 Data" }, JsonRequestBehavior.AllowGet);
                }
                foreach (int item in check)
                {
                    lembur lembur = db.lemburs.Where(e => e.id_lembur == item && e.status == "Pending").FirstOrDefault();
                    lembur.status = "Finish";
                    db.Entry(lembur).State = EntityState.Modified;
                }
                db.SaveChanges();
                return Json(new { success = true, html = Global.RenderRazorViewToString(this, "ListLembur", GetListLembur()), message = check.Length + " Proses Selesai" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult JsonRiwayatLembur()
        {
            return Json(new { success = true, html = Global.RenderRazorViewToString(this, "RiwayatLembur", GetRiwayatLembur()), message = "Proses Selesai" }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult DeleteLembur(int[] check)
        {
            try
            {
                if (check == null)
                {
                    return Json(new { success = false, message = "Check Minimal 1 Data" }, JsonRequestBehavior.AllowGet);
                }
                foreach (int item in check)
                {
                    var lembur = db.lemburs.Where(e => e.id_lembur == item).FirstOrDefault();
                    db.lemburs.Remove(lembur);
                }
                db.SaveChanges();


                return Json(new { success = true, html = Global.RenderRazorViewToString(this, "ListLembur", GetListLembur()), message = "Delete " + check.Length + " Data Sukses" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TugasAkhir/TugasAkhir/Views/lemburs/Create.cshtml
@model TugasAkhir.Models.lembur

@{
    ViewBag.Title = "Add";
    Layout = null;
}

@using (Html.BeginForm("Create", "lemburs", FormMethod.Post, new { enctype = "multipart/form-data", onSubmit = "return ajaxaddlembur(this);", data_restUrl = Url.Action("Create", "lemburs", new { id = 0 }) }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="col-md-5">
                <div class="form-group">
                    @Html.LabelFor(model => model.nik, "Nama", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-7">
                        @Html.DropDownList("ddnama", null, htmlAttributes: new { @class = "form-control chosen-select", id = "ddnama" })
                    </div>
                </div>
                <input type="text" id="textboxnik" name="nik" hidden="hidden" />

                <div class="form-group">
                    @Html.Label("NIK", new { @class = "control-label col-md-4" })
                    <div class="col-md-7">
                        @Html.TextBox("nip", "", htmlAttributes: new { @class = "form-control", @required = "required", id = "textboxnip", @readonly = "readonly", @name = "nip" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.jam_mulai, "Jam Mulai", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.jam_mulai, new { htmlAttributes = new { @class = "form-control cs", @required = "required", type = "time" } })
                        @Html.ValidationMessageFor(model => model.jam_mulai, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.jam_selesai, "Jam Selesai", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.jam_selesai, new { htmlAttributes = new { @class = "form-control cs", @required = "required", type = "time" } })
                        @Html.ValidationMessageFor(model => model.jam_selesai, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("Total Jam Lembur", new { @class = "control-label col-md-4" })
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.total_jam, new { htmlAttributes = new { @class = "form-control cs", id="hasil", type="time", @readonly="readonly" } })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.tanggal, "Tanggal", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.tanggal, new { htmlAttributes = new { @class = "form-control", type = "Date", @required = "required" } })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.reward, "Upah perjam", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.reward, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-4 col-md-8">
                        <button type="submit" class="btn btn-success"><span class="fa fa-save"></span> Submit</button>
                        <button type="reset" class="btn btn-danger"><span class="fa fa-trash-alt"></span> Clear</button>
                    </div>
                </div>
            </div>
                </div>
            </div>
}

TugasAkhir/TugasAkhir/Views/lemburs/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h3>Master Overtime</h3>
<hr />
<ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#pending">Pending</a></li>
    <li><a data-toggle="tab" href="#riwayatlembur">History</a></li>
    <li><a data-toggle="tab" href="#addlembur">Add</a></li>
</ul>
<div class="tab-content">
    <div id="pending" class="tab-pane fade in active">@Html.Action("ListLembur")</div>
    <div id="riwayatlembur" class="tab-pane fade in">@Html.Action("RiwayatLembur")</div>
    <div id="addlembur" class="tab-pane fade in">@Html.Action("Create")</div>
</div>

<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet" />
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src=" https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>

    <script>
        function activatejQueryTable() {
            $('#a').DataTable();           
            $('#z').DataTable();
        }
        $(function () {
            activatejQueryTable();
        });

        $('.cs').change(function () {
            var time1 = $("#jam_mulai").val().split(':'), time2 = $("#jam_selesai").val().split(':');
            var hours1 = parseInt(time1[0]),
                hours2 = parseInt(time2[0]),
                mins1 = parseInt(time1[1]),
                mins2 = parseInt(time2[1]);
            var hours = hours2 - hours1, mins = 0;

            // get hours
            if (hours < 0) hours = 24 + hours;

            // get minutes
            if (mins2 >= mins1) {
                mins = mins2 - mins1;
            }
            else {
                mins = (mins2 + 60) - mins1;
                hours--;
            }

            if (hours < 10) {
                jam = "0";
            } else {
                jam = "";
            }
            if (mins < 10) {
                min = "0";
            } else {
                min = "";
            }

            hours = jam + hours + ":" + min + mins;
            $("#hasil").val(hours);
        
            });

        $('#ddnama').change(function () {
            nik = $('#ddnama').val();
            $.ajax({
                type: "POST",
                url: "lemburs/JsonGetNIP",
                data: { id: nik },
                success: function (result) {
                    $('#textboxnip').val(result);
                },
            });
        });

        $('#ddnama').change(function () {
            $('#textboxnik').val($('#ddnama').val());
        });

       
            $('document').ready(function(){
                $("#ddnama").chosen();
            })

        function GetRiwayatLembur() {
            $.ajax({
                type: "POST",
                url: "lemburs/JsonRiwayatLembur",
                success: function (result) {
                    $("#riwayatlembur").html(result.html);
                    if (typeof activatejQueryTable !== 'undefined' && $.isFunction(activatejQueryTable)) {
                        activatejQueryTable();
                    }
                },
            });
        }

        function EditStatusLembur() {           
            let formdata = $("#asu").serialize();
            Swal.fire({
                title: 'Apakah Anda Yakin?',
                text: "Status reward akan diubah ke finish!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ya',
                cancelButtonText: 'Tidak'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("EditStatus", "lemburs")',
                        data: formdata,
                        success: function (response) {
                            if (response.success) {
                                GetRiwayatLembur();
                                $("#pending").html(response.html);
                                $.notify(response.message, "success");
                                if (typeof activatejQueryTable !== 'undefined' && $.isFunction(activatejQueryTable)) {
                                    activatejQueryTable();
                                    loadcheck();
                                }
                            }
                            else {
                                $.notify(response.message, "error");
                            }
                        }
                    });
                }                
            });
        }

        function DeleteLembur() {                        
            let formdata = $("#asu").serialize();
            Swal.fire({
                title: 'Apakah Anda Yakin?',
                text: "Data lembur ini akan dihapus!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ya',
                cancelButtonText: 'Tidak'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        type: 'GET',
                        url: '@Url.Action("DeleteLembur", "lemburs")',
                        data: formdata,
                        success: function (response) {
                            if (response.success) {                               
                                $("#pending").html(response.html);
                                $.notify(response.message, "warn");
                                if (typeof activatejQueryTable !== 'undefined' && $.isFunction(activatejQueryTable)) {
                                    activatejQueryTable();
                                    loadcheck();
                                }
                            }
                            else {
                                $.notify(response.message, "error");
                            }
                        }
                       
                    });
                }               
            });           
        }

        //Script Select All prosess lembur
        loadcheck();
        function loadcheck() {       
            $('#select_all').on('click', function () {
                if (this.checked) {
                    $('.check').each(function () {
                        this.checked = true;
                    })
                } else {
                    $('.check').each(function () {
                        this.checked = false;
                    })
                }
            });

            $('.check').on('click', function () {
                if ($('.check:checked').length == $('.check').length) {
                    $('#select_all').prop('checked', true)
                } else {
                    $('#select_all').prop('checked', false)
                }
            })           
        }

        function refreshLembur() {
            document.getElementById("jam_mulai").value = "";
            document.getElementById("jam_selesai").value = "";
            document.getElementById("hasil").value = "";
            document.getElementById("reward").value = "";
            document.getElementById("tanggal").value = "";

        }

        function ajaxaddlembur(form) {
            $.validator.unobtrusive.parse(form);
            if ($(form).valid()) {
                var ajaxConfig = {
                    type: 'POST',
                    url: form.action,
                    data: new FormData(form),
                    success: function (response) {
                        if (response.success) {
                            $("#pending").html(response.html);
                            $('ul.nav.nav-tabs a:eq(0)').tab('show');
                            $.notify(response.message, "success");
                            if (typeof activatejQueryTable !== 'undefined' && $.isFunction(activatejQueryTable)) {
                                activatejQueryTable();
                                loadcheck();
                            }
                            refreshLembur();
                        }
                        else {
                            $.notify(response.message, "error");
                        }
                    }
                }
                if ($(form).attr('enctype') == "multipart/form-data") {
                    ajaxConfig["contentType"] = false;
                    ajaxConfig["processData"] = false;
                }
                $.ajax(ajaxConfig);
            }
            return false;
        }
    </script>

}

TugasAkhir/TugasAkhir/Views/lemburs/IndexLemburK.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layoutuser.cshtml";
}
<h3>Overtime Page</h3>
<hr />
<ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#listlemburk">List Overtime</a></li>
    <li><a data-toggle="tab" href="#riwayatlemburk">History Overtime</a></li>
</ul>
<div class="tab-content">
    <div id="listlemburk" class="tab-pane fade in active">@Html.Action("ListLemburK")</div>
    <div id="riwayatlemburk" class="tab-pane fade in">@Html.Action("RiwayatLemburK")</div>
</div>

<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet" />
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src=" https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>

    <script>
        function activatejQueryTable() {
            $('#a').DataTable();
            $('#b').DataTable();
        }
        $(function () {
            activatejQueryTable();
        });

    </script>
}

TugasAkhir/TugasAkhir/Views/lemburs/ListLembur.cshtml
@model IEnumerable<TugasAkhir.Models.lembur>

@{
    ViewBag.Title = "ViewAll";
    Layout = null;
}
<form id="asu" action="">
    <div class="table table-responsive" style="padding-top:5px !important;">
        <table class="table table-striped table-condensed hover" id="a">
            <thead>
                <tr>
                    <th>
                        NIK
                    </th>
                    <th>
                        NAME
                    </th>
                    <th>
                        DATE
                    </th>
                    <th>
                        START HOUR
                    </th>
                    <th>
                        END HOUR
                    </th>
                    <th>
                        TOTAL HOURS
                    </th>
                    <th>
                        REWARD
                    </th>
                    <th>
                        TOTAL REWARD
                    </th>
                    <th>
                        STATUS
                    </th>
                    <th class="text-center" style="padding-left:20px;">
                        <input type="checkbox" id="select_all">
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.user.nip)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.user.nama)
                    </td>
                    <td>
                        @String.Format("{0:dd MMM yyyy}", item.tanggal)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.jam_mulai)<font size="2rem"> WIB</font>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.jam_selesai)<font size="2rem"> WIB</font>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.total_jam)
                    </td>
                    <td>
                        Rp. @String.Format("{0:n}", item.reward)
                    </td>
                    <td>
                        Rp. @String.Format("{0:n}", item.totalreward)
                    </td>
                    <td>
                        @if (item.status == "Pending")
                        {
                            <span class="label label-warning">@Html.DisplayFor(modelItem => item.status)</span>
                        }
                        else
                        {
                            <span class="label label-success">@Html.DisplayFor(modelItem => item.status)</span>
                        }
                    </td>
                    <td class="text-center">
                        <input type="checkbox" name="check" class="check" value="@Html.DisplayFor(modelItem => item.id_lembur)">
                    </td>
                </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th class="text-center">
                        <a onclick="EditStatusLembur()" class="btn btn-primary" title="Lanjut Ke Process"><span class="fa fa-check-circle fa-1x"></span>  Ok</a>
                        <a onclick="DeleteLembur()" title="Delete" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</a>
                    </th>
                </tr>
            </tfoot>
        </table>
    </div>
</form>

TugasAkhir/TugasAkhir/Views/lemburs/ListLemburK.cshtml
@model IEnumerable<TugasAkhir.Models.lembur>

@{
    ViewBag.Title = "ViewAll";
    Layout = null;
}
<div class="table table-responsive" style="padding-top:5px !important;">
    <table class="table table-striped table-condensed hover" id="a">
        <thead>
            <tr>
                <th>
                    DATE
                </th>
                <th>
                    START HOUR
                </th>
                <th>
                    END HOUR
                </th>
                <th>
                    TOTAL HOURS
                </th>
                <th>
                    REWARD
                </th>
                <th>
                    TOTAL REWARD
                </th>
                <th>
                    STATUS
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @String.Format("{0:dd MMM yyyy}", item.tanggal)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.jam_mulai)<font size="2rem"> WIB</font>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.jam_selesai)<font size="2rem"> WIB</font>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.total_jam)
                    </td>
                    <td>
                        Rp. @String.Format("{0:n}", item.reward)
                    </td>
                    <td>
                        Rp. @String.Format("{0:n}", item.totalreward)
                    </td>
                    <td>
                        @if (item.status == "Pending")
                        {
                            <span class="label label-warning">@Html.DisplayFor(modelItem => item.status)</span>
                        }
                        else
                        {
                            <span class="label label-success">@Html.DisplayFor(modelItem => item.status)</span>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

TugasAkhir/TugasAkhir/Views/lemburs/RiwayatLembur.cshtml
@model IEnumerable<TugasAkhir.Models.lembur>

@{
    ViewBag.Title = "ViewAll";
    Layout = null;
}
<div class="table table-responsive" style="padding-top:5px !important;">
    <table class="table table-striped table-condensed hover" id="z">
        <thead>
            <tr>
                <th>
                    NIK
                </th>
                <th>
                    NAME
                </th>
                <th>
                    DATE
                </th>
                <th>
                    START HOUR
                </th>
                <th>
                    END HOUR
                </th>
                <th>
                    TOTAL HOURS
                </th>
                <th>
                    REWARD
                </th>
                <th>
                    TOTAL REWARD
                </th>
                <th>
                    STATUS
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.user.nip)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.user.nama)
                    </td>
                    <td>
                        @String.Format("{0:dd MMM yyyy}", item.tanggal)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.jam_mulai)<font size="2rem"> WIB</font>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.jam_selesai)<font size="2rem"> WIB</font>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.total_jam)
                    </td>
                    <td align="right">
                        Rp. @String.Format("{0:n}", item.reward)
                    </td>
                    <td align="right">
                        Rp. @String.Format("{0:n}", item.totalreward)
                    </td>
                    <td>
                        @if (item.status == "Pending")
                        {
                            <span class="label label-warning">@Html.DisplayFor(modelItem => item.status)</span>
                        }
                        else
                        {
                            <span class="label label-success">@Html.DisplayFor(modelItem => item.status)</span>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>