TugasAkhir/TugasAkhir/Models/user.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TugasAkhir.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Web;
    using System.Web.Mvc;

    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.cutis = new HashSet<cuti>();
            this.lemburs = new HashSet<lembur>();
            this.slipgajis = new HashSet<slipgaji>();
            this.surats = new HashSet<surat>();
            foto_profil = "~/AppFiles/Images/default.png";
        }

        public int nik { get; set; }
        public string nama { get; set; }   
        public string email { get; set; }
        [StringLength(100, ErrorMessage = "Panjang password minimal 6 karakter", MinimumLength = 6)]
        public string password { get; set; }
        public string tempat_lahir { get; set; }
        public Nullable<System.DateTime> tanggal_lahir { get; set; }
        public string jenis_kelamin { get; set; }
        public string no_hp { get; set; }
        public string alamat_domisili { get; set; }
        public string no_ktp { get; set; }
        public string alamat_ktp { get; set; }
        public string pendidikan_akhir { get; set; }
        public string jurusan { get; set; }
        public string agama { get; set; }
        public string npwp { get; set; }
        public string bpjs { get; set; }
        public string status_pajak { get; set; }
        public System.DateTime join_date { get; set; }
        public string no_rekening { get; set; }
        public string jabatan { get; set; }
        public string penempatan { get; set; }
        public string posisi { get; set; }
        public string status_kerja { get; set; }
        public string file_ktp { get; set; }
        public string file_npwp { get; set; }
        public string file_ijasah { get; set; }
        public string file_rekening { get; set; }
        public string foto_profil { get; set; }
        [NotMapped]
        public HttpPostedFileBase foto { get; set; }
        [NotMapped]
        public HttpPostedFileBase filektp { get; set; }
        [NotMapped]
        public HttpPostedFileBase filenpwp { get; set; }
        [NotMapped]
        public HttpPostedFileBase filerekening { get; set; }
        [NotMapped]
        public HttpPostedFileBase fileijasah { get; set; }
        public string nip { get; set; }
        public string oleh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuti> cutis { get; set; }
        public virtual cuti_user cuti_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lembur> lemburs { get; set; }
        public virtual saldo_medical saldo_medical { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<slipgaji> slipgajis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<surat> surats { get; set; }
    }
}

TugasAkhir/TugasAkhir/Controllers/usersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.IO;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TugasAkhir.Models;

namespace TugasAkhir.Controllers
{
    [RoutePrefix("user")]
    public class usersController : Controller
    {
        private dbOpsModel db = new dbOpsModel();

// punya admin
        [HttpGet]
        [ActionName("index")]
        [Route("index")]
        public ActionResult Index()
        {
            if (Session["nik"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (Session["jabatan"].ToString() == "k")
            {
                return RedirectToAction("Karyawan", "Login");
            }
            return View();
        }
        public ActionResult ViewAll()
        {
            return View(GetAllUser());
        }

        IEnumerable<user> GetAllUser()
        {
            int id = Convert.ToInt32(Session["nik"]);
            if (Session["jabatan"].ToString() == "s")
            {
                var users = db.users.Include(u => u.cuti_user).Include(u => u.saldo_medical).Where(u => u.nik != id);
                return users.ToList<user>();
            }
            else
            {
                var users = db.users.Include(u => u.cuti_user).Include(u => u.saldo_medical).Where(u => u.nik != id && u.jabatan == "k");
                return users.ToList<user>();
            }
        
        }

        public ActionResult ResetPassword(string id)
        {
            var user = db.users.Where(u => u.nip == id).FirstOrDefault();         
            if(user != null)
            {
                user emp = db.users.Find(user.nik);
                string nampung = "adins" + DateTime.Today.Year;
                emp.password = md5.encryption(nampung);
                db.Entry(emp).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true, message = "Password berhasil direset menjadi "+nampung }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false, message = "error" }, JsonRequestBehavior.AllowGet);
        }
       

        public ActionResult Details(int id = 0)
        {
            user user = new user();
            if (id != 0)
            {
                user = db.users.Find(id);
            }
            return View(user);   
        }

        public ActionResult AddorEdit(int id = 0)
        {
            user emp = new user();
            if (id != 0)
            {
                emp = db.users.Where(x => x.nik == id).FirstOrDefault<user>();
            }
            else
            {
                var allemp = db.users.Where(x => x.nip.Contains(DateTime.Today.Year.ToString())).ToList();
                int count = allemp.Count + 1;
                string abdul = "";
                if (count <= 9)
                {
                    abdul = "ACE-" + DateTime.Today.Year.ToString() +"-" + "00"+count;
                }
                else if (count <= 100)
                {
                    abdul = "ACE-" + DateTime.Today.Year.ToString() + "-" + "0" + count;
                }
                emp.nip = abdul;
            }  
            return View(emp);
        }

        [HttpPost]
        public ActionResult AddorEdit(user emp, cuti_user cuti, saldo_medical saldo)
        {
            try
            {
                user users = db.users.Find(emp.nik);           
                if (emp.nik == 0)
                {  
                    var cekemail = db.users.Where(u => u.email == emp.email).FirstOrDefault();
                    if (cekemail != null)
                    {
                        return Json(new { success = false, message = "E-Mail sudah terdaftar" }, JsonRequestBehavior.AllowGet);
                    }
                    var ceknip = db.users.Where(u => u.nip == emp.nip).FirstOrDefault();
                    if (ceknip != null)
                    {
                        return Json(new { success = false, message = "NIP sudah terdaftar" }, JsonRequestBehavior.AllowGet);
                    }
                }
                else
                {
                    if (users.email != emp.email)
                    {
                        var cekemail = db.users.Where(u => u.email == emp.email).FirstOrDefault();
                        if (cekemail != null)
                        {
                            return Json(new { success = false, message = "E-Mail sudah terdaftar" }, JsonRequestBehavior.AllowGet);
                        }                   
                    }
                    if (users.nip != emp.nip)
                    {
                        var ceknip = db.users.Where(u => u.nip == emp.nip).FirstOrDefault();
                        if (ceknip != null)
                        {
                            return Json(new { success = false, message = "NIP sudah terdaftar" }, JsonRequestBehavior.AllowGet);
                        }
                    }
                }         
                if (emp.foto != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(emp.foto.FileName);
                    string extension = Path.GetExtension(emp.foto.FileName);
                    fileName = fileName + emp.nama + DateTime.Now.ToString("yymmssffff") + extension;
                    if (emp.nik == 0)
                    {
                      emp.foto_profil = "~/AppFiles/Images/" + fileName;
                    }
                    else {
                        var fotolama = db.users.Where(u => u.nik == emp.nik).FirstOrDefault();
                        var fullpath = Request.MapPath(fotolama.foto_profil);
                        if (emp.foto.ContentType.Contains("image"))
                        {
                        }
                        else
                        {
                            return Json(new { success = false, message = "Format foto profil salah" }, JsonRequestBehavior.AllowGet);
                        }
                        if (fotolama.foto_profil != "~/AppFiles/Images/default.png")
                        {
                            if (System.IO.File.Exists(fullpath))
                            {
                                System.IO.File.Delete(fullpath);
                            }
                        }
                        users.foto_profil = "~/AppFiles/Images/" + fileName;
                    }
                    emp.foto.SaveAs(Path.Combine(Server.MapPath("~/AppFiles/Images/"), fileName));
                }
                if (emp.filektp != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(emp.filektp.FileName);
                    string extension = Path.GetExtension(emp.filektp.FileName);
                    fileName = fileName + emp.nama + DateTime.Now.ToString("yymmssffff") + extension;
                    if (emp.nik == 0)
                    {
                    emp.file_ktp = "~/AppFiles/FileUser/" + fileName;
                    }
                    else
                    {
                        var filelama = db.users.Where(u => u.nik == emp.nik).FirstOrDefault();
                        var fullpath = Request.MapPath(filelama.file_ktp);
                        if (System.IO.File.Exists(fullpath))
                        {
                            System.IO.File.Delete(fullpath);
                        }           
                        users.file_ktp = "~/AppFiles/FileUser/" + fileName;
                    }
                    emp.filektp.SaveAs(Path.Combine(Server.MapPath("~/AppFiles/FileUser/"), fileName));
                }
                if (emp.filenpwp != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(emp.filenpwp.FileName);
                    string extension = Path.GetExtension(emp.filenpwp.FileName);
                    fileName = fileName + emp.nama + DateTime.Now.ToString("yymmssffff") + extension;
                    if (emp.nik == 0)
                    {
                        emp.file_npwp = "~/AppFiles/FileUser/" + fileName;
                    }
                    else
                    {
                        var filelama = db.users.Where(u => u.nik == emp.nik).FirstOrDefault();
                        var fullpath = Request.MapPath(filelama.file_npwp);
                        if (System.IO.File.Exists(fullpath))
                        {
                            System.IO.File.Delete(fullpath);
                        }
                        users.file_npwp = "~/AppFiles/FileUser/" + fileName;
                    }
                    emp.filenpwp.SaveAs(Path.Combine(Server.MapPath("~/AppFiles/FileUser/"), fileName));                  
                    }
                if (emp.filerekening != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(emp.filerekening.FileName);
                    string extension = Path.GetExtension(emp.filerekening.FileName);
                    fileName = fileName + emp.nama + DateTime.Now.ToString("yymmssffff") + extension;
                    if (emp.nik == 0)
                    {
                        emp.file_rekening = "~/AppFiles/FileUser/" + fileName;
                    }
                    else
                    {
                        var filelama = db.users.Where(u => u.nik == emp.nik).FirstOrDefault();
                        var fullpath = Request.MapPath(filelama.file_npwp);
                        if (System.IO.File.Exists(fullpath))
                        {
                            System.IO.File.Delete(fullpath);
                        }
                        users.file_rekening = "~/AppFiles/FileUser/" + fileName;
                    }

TugasAkhir/TugasAkhir/Views/users/Details.cshtml
@model TugasAkhir.Models.user

@{
    ViewBag.Title = "Details";
    Layout = null;
}

<div class="row text-center">
    <img src="@Url.Content(Model.foto_profil)" style="margin:10px;border:1px;border: 5px solid #eaeaea;box-shadow: 1px 1px 10px rgba(0, 0, 0, 0.5);" width="150" height="150" class="img-circle" />
    <h3> @Html.DisplayFor(model => model.nama)</h3>
    <h4> @Html.DisplayFor(model => model.nip)</h4>
    <h4>
        @if (Model.status_kerja == "Aktif")
        {
        <span class="label label-success">Active</span>
        }
        else
        {
        <span class="label label-danger">Non-Active</span>
        }
    </h4>
</div>

<div>
    <hr />
    <div class="col-md-5 col-md-offset-1">
        <table class="table table-striped">
            <tr>
                <th> E-Mail</th>
                <td> @Html.DisplayFor(model => model.email)</td>
            </tr>          
            <tr>
                <th> Tempat, Tgl Lahir</th>
                <td> @Html.DisplayFor(model => model.tempat_lahir), @String.Format("{0:dd MMMM yyyy}", Model.tanggal_lahir)</td>
            </tr>
            <tr>
                <th> Jenis Kelamin</th>
                @if (Model.jenis_kelamin == "L")
                {
                    <td>Laki-Laki </td>
                }
                else
                {
                    <td>Perempuan</td>
                }
            </tr>
            <tr>
                <th> No. Handphone</th>
                <td> @Html.DisplayFor(model => model.no_hp)</td>
            </tr>
            <tr>
                <th> No. KTP</th>
                <td> @Html.DisplayFor(model => model.no_ktp)</td>
            </tr>
            <tr>
                <th> Alamat Domisili</th>
                <td> @Html.DisplayFor(model => model.alamat_domisili)</td>
            </tr>
            <tr>
                <th> Alamat KTP</th>
                <td> @Html.DisplayFor(model => model.alamat_ktp)</td>
            </tr>
            <tr>
                <th> Pendidikan</th>
                <td> @Html.DisplayFor(model => model.pendidikan_akhir)</td>
            </tr>
            <tr>
                <th> Jurusan</th>
                <td> @Html.DisplayFor(model => model.jurusan)</td>
            </tr>
            <tr>
                <th> Agama</th>
                <td> @Html.DisplayFor(model => model.agama)</td>
            </tr>
            <tr>
                <th> NPWP</th>
                <td> @Html.DisplayFor(model => model.npwp)</td>
            </tr>
            <tr>
                <th> Status Pajak</th>
                <td> @Html.DisplayFor(model => model.status_pajak)</td>
            </tr>
            <tr>
                <th> No BPJS</th>
                <td> @Html.DisplayFor(model => model.bpjs)</td>
            </tr>
            <tr>
                <th> Join Date</th>
                <td> @String.Format("{0:dd MMMM yyyy}", Model.join_date)</td>
            </tr>
        </table>
    </div>
    <div class="col-md-5">
        <table class="table table-striped">

            <tr>
                <th> Nomer Rekening</th>
                <td> @Html.DisplayFor(model => model.no_rekening)</td>
            </tr>
            <tr>
                <th> Jabatan</th>
                @if (Model.jabatan == "a")
                {
                    <td>Admin </td>
                }
                else if (Model.jabatan == "s")
                {
                    <td>Super Admin </td>
                }
                else
                {
                    <td>Employee</td>
                }
            </tr>
            <tr>
                <th> Placement</th>
                <td> @Html.DisplayFor(model => model.penempatan)</td>
            </tr>
            <tr>
                <th> Position</th>
                <td> @Html.DisplayFor(model => model.posisi)</td>
            </tr>
            <tr>
                <th> Status</th>
                <td> @Html.DisplayFor(model => model.status_kerja)</td>
            </tr>

            <tr>
                <th> File NPWP </th>
                <td>
                    @if (Model.file_npwp == null)
                    {
                        <font color="red">File NPWP Tidak Ada</font>
                    }
                    else
                    {
                        <a href="@Url.Action("Download", "users", new { filepath = Model.file_npwp.ToString() })"><span class="fa fa-download"></span> Download</a>
                    }
                </td>
            </tr>
            <tr>
                <th> File KTP</th>
                <td>
                    @if (Model.file_ktp == null)
                    {
                        <font color="red">File KTP Tidak Ada</font>
                    }

                    else
                    {
                        <a href="@Url.Action("Download", "users", new { filepath = Model.file_ktp.ToString() })"><span class="fa fa-download"></span> Download</a>
                    }
                </td>
            </tr>
            <tr>
                <th> File Ijazah</th>
                <td>
                    @if (Model.file_ijasah == null)
                    {
                        <font color="red">File Ijazah Tidak Ada</font>
                    }

                    else
                    {
                        <a href="@Url.Action("Download", "users", new { filepath = Model.file_ijasah.ToString() })"><span class="fa fa-download"></span> Download</a>
                    }
                </td>
            </tr>
            <tr>
                <th> File Rekening</th>
                <td>
                    @if (Model.file_rekening == null)
                    {
                        <font color="red">File Rekening Tidak Ada</font>
                    }

                    else
                    {
                        <a href="@Url.Action("Download", "users", new { filepath = Model.file_rekening.ToString() })"><span class="fa fa-download"></span> Download</a>
                    }
                </td>
            </tr>
            @if (Model.jabatan == "k")
            {
                <tr>
                    <th> Saldo Medical Rawat Inap</th>
                    <td> Rp. @String.Format("{0:n}", Model.saldo_medical.saldo_rawatinap) s/d @String.Format("{0:dd MMMM yyyy}", Model.saldo_medical.valid_rawat)</td>
                </tr>
                <tr>
                    <th> Saldo Medical Rawat Jalan</th>
                    <td> Rp. @String.Format("{0:n}", Model.saldo_medical.saldo_rawatjalan) s/d @String.Format("{0:dd MMMM yyyy}", Model.saldo_medical.valid_rawat)</td>
                </tr>
                <tr>
                    <th> Saldo Medical Kacamata</th>
                    <td> Rp. @String.Format("{0:n}", Model.saldo_medical.saldo_kacamata) s/d @String.Format("{0:dd MMMM yyyy}", Model.saldo_medical.valid_kacamata)</td>
                </tr>
                <tr>
                    <th> Jatah Cuti</th>
                    <td> @Html.DisplayFor(model => model.cuti_user.jatah_cuti) s/d @String.Format("{0:dd MMMM yyyy}", Model.cuti_user.valid_jatah)</td>
                </tr>
                <tr>
                    <th> Sisa Jatah Cuti (6 bulan)</th>
                    <td> @Html.DisplayFor(model => model.cuti_user.sisa_cuti) s/d @String.Format("{0:dd MMMM yyyy}", Model.cuti_user.valid_sisa)</td>
                </tr>
            }           
        </table>
    </div>  
</div>

TugasAkhir/TugasAkhir/Views/users/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<h3>Master User</h3>
<hr />
<ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#list">View All</a></li>
    <li><a data-toggle="tab" href="#AddorEdit">Add New</a></li>
    <li id="tab1"><a data-toggle="tab" href="#Details">Detail</a></li>
</ul>
<div class="tab-content">
    <div id="list" class="tab-pane fade in active">@Html.Action("ViewAll")</div>
    <div id="AddorEdit" class="tab-pane fade in">@Html.Action("AddorEdit")</div>
    <div id="Details" class="tab-pane fade in">@Html.Action("Details")</div>
</div>

<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet" />
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src=" https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>

    <script>
        function activatejQueryTable() {
            $('#a').DataTable();
        }
        $(function () {
            activatejQueryTable();
        });

        $('#tab1').hide();
       
        function ResetPassword() {
            let nip = $("#nip").val();
            Swal.fire({
                title: 'Apakah Anda Yakin?',
                text: "Password User Ini Akan Direset ke default!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ya',
                cancelButtonText: 'Tidak'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("ResetPassword", "users")',
                        data: { id : nip },
                        success: function (response) {
                            if (response.success) {
                                $.notify(response.message, "success");
                                if (typeof activatejQueryTable !== 'undefined' && $.isFunction(activatejQueryTable)) {
                                    activatejQueryTable();
                                }
                            }
                            else {
                                $.notify(response.message, "error");
                            }
                        }
                    });
                }                
            });
        }
//Validasi Hanya Angka
        function hanyaAngka(evt) {
            var charCode = (evt.which) ? evt.which : event.keyCode
            if (charCode > 31 && (charCode < 48 || charCode > 57))
                return false;
            return true;
        }
    </script>
}

TugasAkhir/TugasAkhir/Views/users/ViewAll.cshtml
@model IEnumerable<TugasAkhir.Models.user>

@{
    ViewBag.Title = "ViewAll";
    Layout = null;
}
<div class="table table-responsive">
    <table class="table table-striped table-condensed hover" id="a">
        <thead>
            <tr>
                <th>
                    NIK
                </th>
                <th>
                    NAME
                </th>
                <th>
                    E-MAIL
                </th>
                <th>
                    PLACEMENT
                </th>
                <th>
                    BIRTHDAY
                </th>
                <th>
                    JOIN DATE
                </th>
                <th>
                    LEVEL
                </th>
                <th>
                    STATUS
                </th>
                <th>
                    OPTION
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.nip)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.nama)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.penempatan)
                    </td>
                    <td>
                        @String.Format("{0:dd MMM yyyy}", item.tanggal_lahir)
                    </td>
                    <td>
                        @String.Format("{0:dd MMM yyyy}", item.join_date)
                    </td>
                    <td>
                        @if (item.jabatan == "k")
                        {
                            <span class="label label-primary">Employee</span>
                        }
                        else
                        {
                            <span class="label label-warning">Admin</span>
                        }
                    </td>
                    <td>
                        @if (item.status_kerja == "Aktif")
                        {
                            <span class="label label-success">Active</span>
                        }
                        else
                        {
                            <span class="label label-danger">Non-Active</span>
                        }
                    </td>
                    <td>
                        <a onclick="Edit('@Url.Action("AddorEdit", "users", new { id=item.nik})')" title="Edit"><i class="glyphicon glyphicon-edit"></i></a> |
                        <a onclick="Details('@Url.Action("Details", "users", new { id=item.nik})')" title="Details"><i class="glyphicon glyphicon-eye-open"></i></a>
                        @if (Session["jabatan"].ToString() == "s")
                        {
                            <a onclick="Delete('@Url.Action("Delete", "users", new { id=item.nik})')" title="Delete">|<i class="glyphicon glyphicon-trash"></i></a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>