TugasAkhir/TugasAkhir/Models/cuti.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TugasAkhir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuti
    {
        public int id_cuti { get; set; }
        public int nik { get; set; }
        public System.DateTime tanggal { get; set; }
        public System.DateTime durasi_awal { get; set; }
        public System.DateTime durasi_akhir { get; set; }
        public string alamat { get; set; }
        public string no_telp { get; set; }
        public string keterangan { get; set; }
        public string oleh { get; set; }
    
        public virtual user user { get; set; }
    }
}

TugasAkhir/TugasAkhir/Models/cuti_massal.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TugasAkhir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuti_massal
    {
        public int id_massal { get; set; }
        public System.DateTime tanggal { get; set; }
        public string keterangan { get; set; }
        public string oleh { get; set; }
        public Nullable<int> jumlah { get; set; }
    }
}

TugasAkhir/TugasAkhir/Controllers/cutisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.IO;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TugasAkhir.Models;

namespace TugasAkhir.Controllers
{
    public class cutisController : Controller
    {
        private dbOpsModel db = new dbOpsModel();

        // GET: cutis
        public ActionResult Index()
        {
            if (Session["nik"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (Session["jabatan"].ToString() == "k")
            {
                return RedirectToAction("Karyawan", "Login");
            }
            return View();
        }

        public ActionResult CutiMassal()
        {
            return View(GetCutiMassal());
        }

        IEnumerable<cuti_massal> GetCutiMassal()
        {
            var all = db.cuti_massal.OrderBy(u => u.tanggal);
            return all.ToList();
        }

        public ActionResult RiwayatCuti()
        {
            return View(GetRiwayatCuti());
        }

        IEnumerable<cuti> GetRiwayatCuti()
        {
            var all = db.cutis.Include(y => y.user.cuti_user).OrderBy(u => u.tanggal);
            return all.ToList();
        }

        public ActionResult NewCuti()
        {
            ViewBag.ddnama = new SelectList(db.users.Where(u => u.jabatan == "k" && u.status_kerja == "Aktif"), "nik", "nama");
            return View();
        }

        public JsonResult JsonGetNIP(int id)
        {
            var nip = db.users.Where(u => u.nik == id).FirstOrDefault();
            return Json(nip.nip);
        }

        [HttpPost]
        public ActionResult NewCuti(cuti cute)
        {        
            try
            {
                var cutitit = db.cutis.Where(u => u.nik == cute.nik && ((u.durasi_awal >= cute.durasi_awal && u.durasi_awal <= cute.durasi_akhir)||(u.durasi_akhir <= cute.durasi_akhir && u.durasi_akhir >= cute.durasi_awal))).FirstOrDefault();
                if (cutitit != null)
                {
                    return Json(new { success = false, message = "Cuti sudah ada di hari yang sama!" }, JsonRequestBehavior.AllowGet);
                }
                cute.tanggal = DateTime.Today;
                cute.oleh = Session["nama"].ToString();
                db.cutis.Add(cute);
                cuti_user cutis = db.cuti_user.Find(cute.nik);
                int totalhari = Convert.ToInt32((cute.durasi_akhir - cute.durasi_awal).TotalDays);
                totalhari += 1;
                if (totalhari <= 0)
                {
                    return Json(new { success = false, message = "Periksa kembali tanggal yang diinput!" }, JsonRequestBehavior.AllowGet);
                }
                if (cutis.sisa_cuti >= totalhari)
                {
                    cutis.sisa_cuti -= totalhari;
                }
                else
                {
                    cutis.jatah_cuti = (cutis.jatah_cuti + cutis.sisa_cuti) - totalhari;
                    cutis.sisa_cuti = 0;
                }
                db.Entry(cutis).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true, html = Global.RenderRazorViewToString(this, "RiwayatCuti", GetRiwayatCuti()), message = "Input Cuti Sukses!" }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult CutiMassal(FormCollection get)
        {
            try
            {               
                int totalhari = Convert.ToInt32(get["jumlah"]);
                if (totalhari > 0)
                {
                    var emp = db.cuti_user.Include(u => u.user).Where(u => u.user.jabatan == "k" && u.user.status_kerja == "Aktif").ToList();
                    foreach (var cutiemp in emp)
                    {
                        if (cutiemp.sisa_cuti >= totalhari)
                        {
                            cutiemp.sisa_cuti -= totalhari;
                        }
                        else
                        {
                            cutiemp.jatah_cuti = (cutiemp.jatah_cuti + cutiemp.sisa_cuti) - totalhari;
                            cutiemp.sisa_cuti = 0;
                        }
                        db.Entry(cutiemp).State = EntityState.Modified;
                    }
                    cuti_massal cutimassal = new cuti_massal();
                    cutimassal.tanggal = Convert.ToDateTime(get["tanggal"]);
                    cutimassal.keterangan = get["keterangan"];
                    cutimassal.jumlah = totalhari;
                    cutimassal.oleh = Session["nama"].ToString();
                    db.cuti_massal.Add(cutimassal);
                    db.SaveChanges();
                    return Json(new { success = true, html = Global.RenderRazorViewToString(this, "CutiMassal", GetCutiMassal()), message = "Input cuti massal sukses!" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, message = "Input tidak valid" }, JsonRequestBehavior.AllowGet);
                }              
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }


        //punya karyawan

        [HttpGet]
        public ActionResult IndexCutiK()
        {
            if (Session["nik"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (Session["jabatan"].ToString() != "k")
            {
                return RedirectToAction("Admin", "Login");
            }
            int id = Convert.ToInt32(Session["nik"]);
            cuti_user cek = db.cuti_user.Find(id);
            ViewBag.jatah = cek.jatah_cuti;
            ViewBag.sisa = cek.sisa_cuti;
            ViewBag.validjatah = cek.valid_jatah;
            ViewBag.validsisa = cek.valid_sisa;
            return View();
        }

        public ActionResult RiwayatCutiK()
        {
            return View(GetRiwayatCutiK());
        }

        IEnumerable<cuti> GetRiwayatCutiK()
        {
            int id = Convert.ToInt32(Session["nik"]);
            var all = db.cutis.Include(y => y.user.cuti_user).Where(u => u.nik == id).OrderBy(u => u.tanggal);
            return all.ToList();
        }

        public ActionResult Details(int id = 0)
        {
            cuti cute = new cuti();
            if (id != 0) 
            {
                cute = db.cutis.Find(id);
            }
            return View(cute);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TugasAkhir/TugasAkhir/Views/cutis/CutiMassal.cshtml
@model IEnumerable<TugasAkhir.Models.cuti_massal>

@{
    ViewBag.Title = "ViewAll";
    Layout = null;
}
<div class="table table-responsive" style="padding-top:5px !important;">
    <table class="table table-striped table-condensed hover" id="b">
        <thead>
            <tr>
                <th>
                    DATE
                </th>
                <th>
                    TOTAL DAYS
                </th>
                <th>
                    ANNOTATION
                </th>
                @if (Session["jabatan"].ToString() != "k")
                {
                    <th>
                        ADDED BY
                    </th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @String.Format("{0:dd MMMM yyyy}", item.tanggal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.jumlah)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.keterangan)
                </td>
                @if (Session["jabatan"].ToString() != "k")
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.oleh)
                    </td>
                }
            </tr>
            }
        </tbody>
    </table>
</div>

TugasAkhir/TugasAkhir/Views/cutis/Details.cshtml
@model TugasAkhir.Models.cuti

@{
    ViewBag.Title = "Detail Cuti";
    Layout = null;
}

<div>
    <hr />
    <div class="col-md-6">
        <table class="table table-striped">
            <tr>
                <th>NIK</th>
                <td> @Html.DisplayFor(model => model.user.nip)</td>
            </tr>
            <tr>
                <th>Nama</th>
                <td> @Html.DisplayFor(model => model.user.nama)</td>
            </tr>
            <tr>
                <th>E-Mail</th>
                <td> @Html.DisplayFor(model => model.user.email)</td>
            </tr>
            <tr>
                <th> Tanggal Awal</th>
                <td> @String.Format("{0:dd MMMM yyyy}", Model.durasi_awal)</td>
            </tr>
            <tr>
                <th> Tanggal Akhir</th>
                <td> @String.Format("{0:dd MMMM yyyy}", Model.durasi_akhir)</td>
            </tr>
            <tr>
                <th>Alamat</th>
                <td> @Html.DisplayFor(model => model.alamat)</td>
            <tr>
                <th>No.Telp</th>
                <td> @Html.DisplayFor(model => model.no_telp)</td>
            </tr>
            <tr>
                <th>Jatah Cuti</th>
                <td> @Html.DisplayFor(model => model.user.cuti_user.jatah_cuti)</td>
            </tr>
            <tr>
                <th>Sisa Cuti</th>
                <td> @Html.DisplayFor(model => model.user.cuti_user.sisa_cuti)</td>
            </tr>
        </table>
    </div> 
</div>

TugasAkhir/TugasAkhir/Views/cutis/Index.cshtml
@{
    ViewBag.Title = "Index Claim";
}
<h3>Master Annual Leave</h3>
<a href="#" data-toggle="modal" data-target="#myModal" style="text-decoration-line:none;" class="btn btn-primary"><i class="fa fa-plane"></i> Add Holiday</a>
<hr />
<ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#riwayatcuti">History</a></li>
    <li><a data-toggle="tab" href="#cutimassal">Holiday History</a></li>
    <li><a data-toggle="tab" href="#newcuti">Add Annual Leave</a></li>
    <li id="tab1"><a data-toggle="tab" href="#detailcuti">Detail</a></li>
</ul>
<div class="tab-content">
    <div id="riwayatcuti" class="tab-pane fade in active">@Html.Action("RiwayatCuti")</div>
    <div id="cutimassal" class="tab-pane fade in">@Html.Action("CutiMassal")</div>
    <div id="newcuti" class="tab-pane fade in">@Html.Action("NewCuti")</div>
    <div id="detailcuti" class="tab-pane fade in">@Html.Action("Details")</div>
</div>

<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- konten modal-->
        <div class="modal-content">
            <!-- heading modal -->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h1 class="modal-title text-center" style="font-family:'Engravers MT'; font-size:xx-large;"><i class="fa fa-plane"></i> <b>Cuti Massal</b></h1>
            </div>
            <!-- body modal -->
            @using (Html.BeginForm("CutiMassal", "cutis", FormMethod.Post, new { enctype = "multipart/form-data", onSubmit = "return ajaxcutimassal(this);", @class = "form-horizontal" }))
            {
            <div class="modal-body">

                <div class="form-group">
                    @Html.Label("Jumlah Cuti", new { @class = "control-label col-md-3" })
                    <div class="col-md-7">
                        <input type="number" class="form-control" name="jumlah" required />
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("Tanggal", new { @class = "control-label col-md-3" })
                    <div class="col-md-7">
                        <input type="date" class="form-control" name="tanggal" required />
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("Keterangan", new { @class = "control-label col-md-3" })
                    <div class="col-md-7">
                        <input type="text" class="form-control" name="keterangan" required />
                    </div>
                </div>
            </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-success"><span class="fa fa-save"></span> Submit</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-window-close"></i> Close</button>
                </div>
            }
            </div>
    </div>
</div>

<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet" />
@*<link href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.dataTables.min.css" rel="stylesheet" />*@
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
    @*<script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
        <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.flash.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
        <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
        <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>*@


    <script>

        function activatejQueryTable() {
            //$('#a').DataTable({
            //    dom: 'Bfrtip',
            //    buttons: [
            //        'excel'
            //    ]
            //});
            $('#a').DataTable();
            $('#b').DataTable();
        }
        $(function () {
            activatejQueryTable();
        });

        $('#ddnama').change(function () {
            nik = $('#ddnama').val();
            $.ajax({
                type: "POST",
                url: "cutis/JsonGetNIP",
                data: { id: nik },
                success: function (result) {
                    $('#textboxnip').val(result);
                },
            });
        });

        $('#ddnama').change(function () {
            $('#textboxnik').val($('#ddnama').val());
        });


        $('document').ready(function () {
            $("#ddnama").chosen();
        })

        $('#tab1').hide();
        
        function DetailCuti(url) {
            $.ajax({
                type: 'GET',
                url: url,
                success: function (response) {
                    $('#tab1').show();
                    $("#detailcuti").html(response);
                    $('ul.nav.nav-tabs a:eq(3)').tab('show');
                }
            });
        }


        function ajaxaddcuti(form) {
            $.validator.unobtrusive.parse(form);
            if ($(form).valid()) {
                var ajaxConfig = {
                    type: 'POST',
                    url: form.action,
                    data: new FormData(form),
                    success: function (response) {
                        if (response.success) {
                            $('#tab1').hide();
                            $("#riwayatcuti").html(response.html);
                            $('ul.nav.nav-tabs a:eq(0)').tab('show');
                            $.notify(response.message, "success");
                            if (typeof activatejQueryTable !== 'undefined' && $.isFunction(activatejQueryTable)) {
                                activatejQueryTable();
                            }
                        }
                        else {
                            $.notify(response.message, "error");
                        }
                    }
                }
                if ($(form).attr('enctype') == "multipart/form-data") {
                    ajaxConfig["contentType"] = false;
                    ajaxConfig["processData"] = false;
                }
                $.ajax(ajaxConfig);
            }
            return false;
        }

        function ajaxcutimassal(form) {         
                $.validator.unobtrusive.parse(form);
                if ($(form).valid()) {
                    var ajaxConfig = {
                        type: 'POST',
                        url: form.action,
                        data: new FormData(form),
                        success: function (response) {
                            if (response.success) {
                                $('#tab1').hide();
                                $('#myModal').modal('hide');
                                $("#cutimassal").html(response.html);
                                $('ul.nav.nav-tabs a:eq(1)').tab('show');
                                $.notify(response.message, "success");
                                if (typeof activatejQueryTable !== 'undefined' && $.isFunction(activatejQueryTable)) {
                                    activatejQueryTable();
                                }
                            }
                            else {
                                $.notify(response.message, "error");
                            }
                        }
                    }
                    if ($(form).attr('enctype') == "multipart/form-data") {
                        ajaxConfig["contentType"] = false;
                        ajaxConfig["processData"] = false;
                    }
                    $.ajax(ajaxConfig);
                }
                return false;
            }
     

    </script>
}

TugasAkhir/TugasAkhir/Views/cutis/IndexCutiK.cshtml
@{
    ViewBag.Title = "Cek Cuti";
    Layout = "~/Views/Shared/_Layoutuser.cshtml";
}
<h3>Annual Leave</h3>
<a href="#" data-toggle="modal" data-target="#myModal" style="text-decoration-line:none;" class="btn btn-primary"><i class="fa fa-money-bill-alt"></i> Annual Leave Quota</a>
<hr />
<ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#riwayatcuti">History</a></li>
    <li><a data-toggle="tab" href="#cutimassal">Holiday History</a></li>
    <li id="tab1"><a data-toggle="tab" href="#detailcuti">Detail</a></li>
</ul>
<div class="tab-content">
    <div id="riwayatcuti" class="tab-pane fade in active">@Html.Action("RiwayatCutiK")</div>
    <div id="cutimassal" class="tab-pane fade in">@Html.Action("CutiMassal")</div>
    <div id="detailcuti" class="tab-pane fade in">@Html.Action("Details")</div>
</div>


<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- konten modal-->
        <div class="modal-content" style="border-radius: 20px;">
            <!-- heading modal -->
            <div class="modal-header">                
                <h1 class="modal-title text-center" style="font-family:'Engravers MT'; font-size:xx-large;"><i class="fa fa-bullhorn"></i> <b>Info Cuti Anda</b></h1>
            </div>
            <!-- body modal -->
            <div class="modal-body">                
                <h3 style="font-family:'Californian FB'">Jatah cuti anda : <b>@ViewBag.jatah</b> s/d <b>@String.Format("{0:dd MMMM yyyy}", ViewBag.validjatah)</b></h3><br />
                <h3 style="font-family:'Californian FB'">Sisa cuti anda : <b>@ViewBag.sisa</b> s/d <b>@String.Format("{0:dd MMMM yyyy}", ViewBag.validsisa)</b></h3><br />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-window-close"></i> Close</button>
            </div>
        </div>
    </div>
</div>

<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet" />
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src=" https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>

    <script>
        function activatejQueryTable() {
            $('#a').DataTable();
            $('#b').DataTable();
        }
        $(function () {
            activatejQueryTable();
        });

        $('#tab1').hide();


        function DetailCutiK(url) {
            $.ajax({
                type: 'GET',
                url: url,
                success: function (response) {
                    $('#tab1').show();
                    $("#detailcuti").html(response);
                    $('ul.nav.nav-tabs a:eq(1)').tab('show');
                }
            });
        }

    </script>
}

TugasAkhir/TugasAkhir/Views/cutis/NewCuti.cshtml
@model TugasAkhir.Models.cuti

@{
    ViewBag.Title = "Add Cuti";
    Layout = null;
}

@using (Html.BeginForm("NewCuti", "cutis", FormMethod.Post, new { enctype = "multipart/form-data", onSubmit = "return ajaxaddcuti(this);" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="col-md-5">
                <div class="form-group">
                    @Html.LabelFor(model => model.nik, "Nama", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-7">
                        @Html.DropDownList("ddnama", null, htmlAttributes: new { @class = "form-control chosen-select", id = "ddnama" })
                    </div>
                </div>
                <input type="text" id="textboxnik" name="nik" hidden="hidden" />

                <div class="form-group">
                    @Html.Label("NIK", new { @class = "control-label col-md-4" })
                    <div class="col-md-7">
                        @Html.TextBox("nip", "", htmlAttributes: new { @class = "form-control", @required = "required", id = "textboxnip", @readonly = "readonly", @name = "nip" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.durasi_awal, "Durasi Awal", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.durasi_awal, new { htmlAttributes = new { @class = "form-control", type = "Date", @required = "required" } })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.durasi_akhir, "Durasi Akhir", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.durasi_akhir, new { htmlAttributes = new { @class = "form-control", type = "Date", @required = "required" } })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.alamat, "Alamat Cuti", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-7">
                        @Html.TextAreaFor(model => model.alamat, new { @class = "form-control", @rows = "3", @required = "required" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.no_telp, "No Telp Saat Cuti", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.no_telp, new { htmlAttributes = new { @class = "form-control", type = "Number", @required = "required" } })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.keterangan, "Keterangan Cuti", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.keterangan, new { htmlAttributes = new { @class = "form-control", type = "text", @required = "required" } })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn btn-success"><span class="fa fa-save"></span> Submit</button>
                        <button type="reset" class="btn btn-danger"><span class="fa fa-trash-alt"></span> Clear</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

TugasAkhir/TugasAkhir/Views/cutis/RiwayatCuti.cshtml
@model IEnumerable<TugasAkhir.Models.cuti>

@{
    ViewBag.Title = "ViewAll";
    Layout = null;
}
<div class="table table-responsive" style="padding-top:5px !important;">
    <table class="table table-striped table-condensed hover" id="a">
        <thead>
            <tr>
                <th>
                    NIK
                </th>
                <th>
                    NAME
                </th>
                <th>
                    SUBMISSION DATE
                </th>
                <th>
                    START DATE
                </th>
                <th>
                    END DATE
                </th>
                <th>
                    ANNOTATION
                </th>
                @if (Session["jabatan"].ToString() != "k")
                {
                    <th>
                        BY
                    </th>
                }
                <th>
                    OPTIONS
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.user.nip)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.user.nama)
                </td>
                <td>
                    @String.Format("{0:dd MMMM yyyy}", item.tanggal)
                </td>
                <td>
                    @String.Format("{0:dd MMMM yyyy}", item.durasi_awal)
                </td>
                <td>
                    @String.Format("{0:dd MMMM yyyy}", item.durasi_akhir)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.keterangan)
                </td>
                @if (Session["jabatan"].ToString() != "k")
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.oleh)
                    </td>
                }
                <td>
                    <a onclick="DetailCuti('@Url.Action("Details", "cutis", new { id = item.id_cuti })')" title="Details"><i class="glyphicon glyphicon-eye-open"></i></a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

TugasAkhir/TugasAkhir/Views/cutis/RiwayatCutiK.cshtml
@model IEnumerable<TugasAkhir.Models.cuti>

@{
    ViewBag.Title = "ViewAll";
    Layout = null;
}
<div class="table table-responsive" style="padding-top:5px !important;">
    <table class="table table-striped table-condensed hover" id="a">
        <thead>
            <tr>
                <th>
                    NIK
                </th>
                <th>
                    NAME
                </th>
                <th>
                    SUBMISSION DATE
                </th>
                <th>
                    START DATE
                </th>
                <th>
                    END DATE
                </th>
                <th>
                    ANNOTATION
                </th>
                <th>
                    OPTIONS
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.user.nik)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.user.nama)
                    </td>
                    <td>
                        @String.Format("{0:dd MMMM yyyy}", item.tanggal)
                    </td>
                    <td>
                        @String.Format("{0:dd MMMM yyyy}", item.durasi_awal)
                    </td>
                    <td>
                        @String.Format("{0:dd MMMM yyyy}", item.durasi_akhir)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.keterangan)
                    </td>
                    <td>
                        <a onclick="DetailCutiK('@Url.Action("Details", "cutis", new { id = item.id_cuti })')" title="Details"><i class="glyphicon glyphicon-eye-open"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>